### ISSUE TITLE
LectureRequest_CKA

### ISSUE THREAD

**Issue by saradaathavale** [mmumshad/kubernetes-the-hard-way#169]
Hi Sir,
     No live project of ours is complete without splunk setup for log onboarding and datadog for metrics and alerts. I would really like to see these topics covered in the lecture. We also use helm for deployments and Istio gateway and Istio Injection. Would like to understand these basics. Please see if these can be covered.

**Comment by fireflycons** [comment]
Hi @saradaathavale 

Since Kubernetes 1.21 Helm is part of CKAD and is covered by our lectures.
We also have dedicated Helm and Istio courses at https://kodekloud.com

You can raise requests for new courses by going to the following link. If something similar to what you're looking for is already present in the list, simply upvote it else add a new request.
Thanks.

https://kodekloud.com/request-a-course/
