### ISSUE TITLE
Unable to ssh to any of the nodes 

### ISSUE THREAD

**Issue by SUK1** [mmumshad/kubernetes-the-hard-way#210]
unbale to ssh to any of the nodes , i can not even ping nodes after they were created by using vagrant file 
can you help on this 

2nd question ==> if i have to login to vm systes manullay what is the username & password is should using

**Comment by cweitay93** [comment]
Encountered this issue when running `vagrant ssh <vm>` on Win10 due to the built-in SSH client. Fixed it with the following steps:
1. Edit environment variables
2. Add 'path\to\Vagrant\embedded\usr\bin' entry. In my case: 'C:\HashiCorp\Vagrant\embedded\usr\bin' 
3. Remove 'C:\Windows\System32\OpenSSH\' or shift it below the entry added in pt. 2.
4. Run the vagrant ssh command again and it should use the correct ssh executable.

Hope this helps.

**Comment by fireflycons** [comment]
Hi @SUK1 @cweitay93 

Odd. I have a windows 10 machine with `C:\Windows\System32\OpenSSH\ssh.exe` and faced no such issue.

I installed Vagrant using chocolatey and `vagrant ssh` works out the box.

With regard to manual login, the username and password are both `vagrant`

We have now merged a major change to bring this to v1.24, so you may like to run through the new version to see what's changed.
