### ISSUE TITLE
CrashLoopBackOff error on the Weave Net

### ISSUE THREAD

**Issue by hashirph** [mmumshad/kubernetes-the-hard-way#321]
The Core DNS update is not working and the weave networking also seems not working.

vagrant@master-1:~$ kubectl get pods -n kube-system
NAME                       READY   STATUS              RESTARTS         AGE
coredns-6f4b4bd8fb-gkgpl   0/1     ContainerCreating   0                24h
coredns-6f4b4bd8fb-pf2jz   0/1     ContainerCreating   0                24h
weave-net-jhzs7            1/2     CrashLoopBackOff    144 (118s ago)   39h
weave-net-wxk9r            1/2     CrashLoopBackOff    143 (45s ago)    39h

vagrant@master-1:~$ kubectl logs weave-net-jhzs7 -n kube-system
Defaulted container "weave" out of: weave, weave-npc, weave-init (init)
FATA: 2023/07/05 05:09:36.639718 [kube-peers] Could not get peers: Get "https://10.96.0.1:443/api/v1/nodes": dial tcp 10.96.0.1:443: i/o timeout
Failed to get peers

**Comment by asdasdqqq** [comment]
I have the same problem.
$ kubectl logs weave-net-gscrg -n kube-system
Defaulted container "weave" out of: weave, weave-npc, weave-init (init)
FATA: 2023/09/01 07:32:44.454828 [kube-peers] Could not get peers: Get "https://10.96.0.1:443/api/v1/nodes": dial tcp 10.96.0.1:443: i/o timeout
Failed to get peers

**Comment by fireflycons** [comment]
Hello
@hashirph The instructions in this lab have not changed since it was last tested. You have most likely made an error in one of the previous steps - check what it says about that in this section https://github.com/mmumshad/kubernetes-the-hard-way#kubernetes-the-hard-way-on-virtualbox

@asdasdqqq Gald you got it to work on proxmox. It _should_ work on any hypervisor, however the instructions here only detail how to configure a VirtualBox network. We couldn't really cover every possible hypervisor solution.
